name: CD

on:
  push:
    tags:
      - '*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Github Docker login
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker build
        run: |
          version="${GITHUB_REF/refs\/tags\//}"
          minor_version="${version%.*}"
          major_version="${minor_version%.*}"
          docker build . \
              --tag ghcr.io/hoshsadiq/crond:$version \
              --tag ghcr.io/hoshsadiq/crond:$minor_version \
              --tag ghcr.io/hoshsadiq/crond:$major_version \
              --tag ghcr.io/hoshsadiq/crond:latest \
              --build-arg DATE="$(date --rfc-3339=seconds | sed 's/ /T/')" \
              --build-arg PROJECT_NAME="${{ github.repository }}" \
              --build-arg FULL_COMMIT="${{ github.sha }}" \
              --build-arg VERSION="$version"

          docker push ghcr.io/hoshsadiq/crond:$version
          docker push ghcr.io/hoshsadiq/crond:$minor_version
          docker push ghcr.io/hoshsadiq/crond:$major_version
          docker push ghcr.io/hoshsadiq/crond:latest
